name: Build iohook

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: # This line allows manual triggering of the workflow


jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all --openssl_fips=''

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Windows Prebuilds
          path: prebuilds

  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64, arm64] # Define the architectures

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci --ignore-scripts

      # Replace the following line with your actual build command for the specified architecture
      - name: Build for ${{ matrix.architecture }}
        run: npm run build -- --all --arch=${{ matrix.architecture }} --target_arch=${{ matrix.architecture }}

      - name: Upload build artifacts for ${{ matrix.architecture }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: macOS Prebuilds ${{ matrix.architecture }}
          path: prebuilds
        

  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          sudo apt-get update
      - name: Install dependencies (Ubuntu)
        run: sudo apt-get install libxtst-dev

      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Linux (Ubuntu) Prebuilds
          path: prebuilds
